name: taranis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - python>=3.6
  - bioconda::blast=2.5
  - bioconda::mash=1.1
  - bioconda::prodigal=2.6.3
  - bioconda::prokka=1.12
 
  - pip:
    - biopython==1.72
    - pandas==1.2.4
    - progressbar==2.5
    - openpyxl==3.0.7
    - plotly==5.0.0
    - numpy==1.20.3


